<!DOCTYPE html>
<html>
    <head>
        <title>Damn Vulnerable Imageboard</title>
        <style>
            label {
                display: block;
            }
            .post {
                border-width: 1px;
                border-style: solid;
                padding: 1em;
                margin: 1em;
            }
            img {
                max-width: 100%;
            }
            #menu { 
    	  padding:0; 
    	  margin: 0; 
    	  } 
    	#menu li { 
            padding-right: .5em;
    	  list-style-type:none; 
          display: inline;
    	  } 
        </style>
    </head>
    <body>
